theme: jekyll-theme-minimal
title: Buzz, bust, and bounce-back
description: data-driven strategy to deal with YouTubers’ decline
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Test
    url: test
